version: '3.4'


networks:
  abcblogapiservicenetwork:

services:
  abcblog.api:
    image: abcblog.api:latest
    build:
      context: .
      dockerfile: ./tools/docker/Dockerfile
    networks:
      - abcblogapiservicenetwork
    ports:
      - "1453:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development